studentapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  resources :groups
  resources :marks
  root 'students#index' 
end

studentapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

studentapp/app/models/group.rb
class Group < ApplicationRecord
	has_many :group_students
	accepts_nested_attributes_for :group_students 
	has_many :students,through: :group_students	
end

studentapp/app/models/group_student.rb
class GroupStudent < ApplicationRecord
  belongs_to :student
  belongs_to :group
end

studentapp/app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  belongs_to :subject
end

studentapp/app/models/student.rb
class Student < ApplicationRecord
	validates :name, presence: true
	validates :email, :presence => true, :uniqueness => true                      
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	has_many :marks
	has_many :groups, through: :group_students
	has_many :group_students
	#method for calculating weighted average
	def weighted_average(student) 
		mark_array = []
		student.marks.each do |f|
			if f.subject.name == "Physics"		
				@weighted_phy = f.mark * 0.30
				mark_array << (f.mark * 0.30).round(2)
			elsif f.subject.name == "Chemistry"				
				@weighted_che = f.mark * 0.20
				mark_array << (f.mark * 0.20).round(2)
			elsif f.subject.name == "Maths"				
				@weighted_maths = (f.mark * 0.40)
				mark_array << (f.mark * 0.40).round(3)
			else
				@weighted_english = f.mark * 0.10
				mark_array << (f.mark * 0.10).round(3)
			end
		end
		@total_weighted_average = (@weighted_phy.to_f + @weighted_che.to_f + @weighted_maths.to_f + @weighted_english.to_f ) / 4	
		return mark_array, @total_weighted_average
	end	
end

studentapp/app/models/subject.rb
class Subject < ApplicationRecord
	has_many :marks
end

studentapp/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

studentapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

studentapp/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def new
		@group = Group.new
	end
	def create
		if !Group.find_by_name(params[:group][:name])
			@group = Group.create(params_of_group)
		else
			@group = Group.find_by_name(params[:group][:name])
		end
		@group_data = Group.find(@group.id)
		student_details = Student.find(params[:group][:students][:students_id])
		respond_to do |format|
			if @group_data.students << student_details
				format.html { redirect_to new_group_path, notice: 'Group Created' }
      	format.json { head :no_content }
      else
      	format.html { render action: 'new' }
      	format.json { render json: @group_data.errors, status: :unprocessable_entity }
      end
    end
	end
	
	private
		def params_of_group
			params.require(:group).permit(:name,:students)
		end
end

studentapp/app/controllers/marks_controller.rb
class MarksController < ApplicationController
	def new
		@mark = Mark.new
	end
	def create		
		@mark = Mark.new(mark_params)
		respond_to do |format|
			if @mark.save
      	format.html { redirect_to new_mark_path, notice: 'Mark Added' }
      	format.json { head :no_content }
    	else
      	format.html { render action: 'new' }
      	format.json { render json: @mark.errors, status: :unprocessable_entity }
    	end
    end
	end
	
private
	def mark_params
		params.require(:mark).permit(:student_id,:subject_id,:mark)
	end
end

studentapp/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all		
	end
	def new
		@student = Student.new
		@students = Student.all		
	end
	def create
		@students = Student.all	
		@student = Student.create(student_params)
		respond_to do |format|
			if @student.save
        format.js
     	else
      	format.html { render 'new', notice: 'Student  Not Added' }
      	format.json { head :no_content }
    	end
    end
	end	
	def show	
		@student = Student.find(params[:id])		
		@marks_array, @total_weighted_average = @student.weighted_average(@student)	
	end

private
	def student_params
		params.require(:student).permit(:name,:email)
	end
end

studentapp/app/helpers/application_helper.rb
module ApplicationHelper
end

studentapp/app/helpers/students_helper.rb
module StudentsHelper
end

studentapp/app/views/groups/new.html.erb
<%= form_for @group, :url => { :action => :create } do |f| %>
	<%= f.label :Group_Name %>
	<%= f.text_field :name %>
	</br>
	</br>
	<%= f.fields_for :students do |line| %>
		<%= line.label :students %>
		<%= line.collection_select(:students_id, Student.all, :id, :name , {include_blank: 'Select Student'} ) %>
	</br>
	</br>
	<% end %>
	<%= f.submit %>
	
<% end %>

studentapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<p class="navbar-text pull-right">
			<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= link_to "Back", students_path %>
			<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
		</p>
   	<%= yield %>
  </body>
</html>

studentapp/app/views/marks/new.html.erb
<%= form_for @mark do |f| %>
	<%= f.label :Student %>
	<%= f.collection_select(:student_id, Student.all, :id, :name ,  {include_blank: 'Select Student'} )%>
	<%= f.label :Subject %>
	<%= f.collection_select(:subject_id, Subject.all, :id, :name , {include_blank: 'Select Subject'} ) %>
	<%= f.label :mark %>
	<%= f.text_field :mark %>
	<%= f.submit %>
<% end %>

	

studentapp/app/views/marks/report.html.erb
<html>
	<head>
	</head>
	<body>
		<%= form_for :mark,:url => {:action => "weighted_avg"},:method => :get  do |f| %>
			<%= f.label :Student %>
			<%= f.collection_select(:student_id, Student.all, :id, :name ,  {include_blank: 'Select Student'} )%>
			<%= f.submit "Get Report",  :id => "butt"%>
		<% end %>
	</body>
</html>

studentapp/app/views/marks/weighted_avg.html.erb
<h1>
Student Report
</h1>

studentapp/app/views/students/_display.html.erb
<table border=1>
	<tr>
		<td>
			<b>Name
		</td>
		<td>
			<b> Email 
		</td>
	</tr>
	<% @students.each do |f| %>	
	<tr>
		<td>
			<%= f.name %>
		</td>
		<td>
			<%= f.email %>
		</td>
		<td>
			<%= link_to "Get Report", student_path(f.id) %>
		</td>
	</tr>
	<% end %>
</table>

studentapp/app/views/students/_form.html.erb
<%= form_for @student, remote: true do |f| %>
	<%= f.label :Name %>
	<%= f.text_field :name %>
	<br>
	<br>
	<%= f.label :Email %>
	<%= f.text_field :email %>
	<br>
		<br>
		<%= f.submit :class => 'submit_me' %>
<% end %>

studentapp/app/views/students/create.js.erb
$("#new_div").append("<table border = '1'> <tr id ='<%= @student.id %>'>\n  <td><%= @student.name %><\/td>\n  <td><%= @student.email %><\/td>\n <td><%= escape_javascript link_to('Get Report', student_path(@student.id)) %><\/td>\n<\/tr>\n</table>" );
document.getElementById("new_student").reset();

studentapp/app/views/students/index.html.erb
<div id="show-timeline">
	<%= link_to "Add Student",new_student_path %>
	</br>
	<%= link_to "Add Group", new_group_path %>
  </br>
	<%= link_to "Add Mark", new_mark_path %>
  <%= render 'display' %>
</div>

studentapp/app/views/students/new.html.erb
<div id="my-timeline-box">
  <%= render 'form' %>
<div id = "new_div", class = "new_div">
  <%= render 'display' %>
</div>
</div>

studentapp/app/views/students/show.html.erb
<html>
	<head>
	</head>
	<body>
		<table border = 1>
			<tr>
				<td> 
					Name
				</td>
				<td>
					Score of Physics
				</td>
				<td>
					Score of Chemistry
				</td>
				<td>
					Score of maths
				</td>
				<td>
					Score of English
				</td>
				<td>
					Total weighted average
				</td>
			</tr>
			<tr>
				<td>
					<%= @student.name %>
				</td>

				<td>
					<%= @marks_array[0] %>
				</td>
				<td>
					<%= @marks_array[1] %>
				</td>
				<td>
					<%= @marks_array[2] %>
				</td>
				<td>
					<%= @marks_array[3] %>
				</td>
				<td>
					<%= @total_weighted_average %>
				</td>
			</tr>
		</table>
	</body>
</html>